<table align="left" width=100%>
    <tr>
        <td width="10%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> 9. Semantic Analysis </b>
                </font>
            </div>
        </td>
    </tr>
</table>

<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/vidyadharbendre/learn_nlp_using_examples/blob/main/notebooks/09_Semantic_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
  <td>
    <a target="_blank" href="https://kaggle.com/kernels/welcome?src=https://github.com/vidyadharbendre/learn_nlp_using_examples/blob/main/notebooks/09_Semantic_Analysis.ipynb"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" /></a>
  </td>
</table>

## What is Semantic Analysis?
Semantic Analysis is the process of understanding the meaning and interpretation of words, phrases, and sentences in context. It involves analyzing the relationships and meanings of words to determine the intended message of the text.

## Why Semantic Analysis?
Semantic Analysis is essential for:

Improving the accuracy of NLP tasks like sentiment analysis, machine translation, and information retrieval.
Enhancing the understanding of context and meaning in text.
Supporting more sophisticated text analysis and interpretation.

## How to Achieve Semantic Analysis Programmatically?
Using SpaCy:

In [1]:
import spacy

# Print the version of SpaCy installed
print(spacy.__version__)

3.5.4


In [2]:
import spacy

# Print the version of SpaCy installed
print(spacy.__version__)

3.5.4


In [3]:
import spacy

# Print the version of SpaCy installed
print(spacy.__version__)

3.5.4


In [4]:
import spacy

# Load SpaCy's English language model
nlp = spacy.load("en_core_web_sm")

# Example text
text = "Apple is looking at buying a U.K. startup for $1 billion."

# Process the text with SpaCy
doc = nlp(text)

# Semantic analysis using SpaCy
semantic_analysis_spacy = [(token.text, token.vector) for token in doc]

# Display token text and vector
for token_text, token_vector in semantic_analysis_spacy:
    print(f"Token: {token_text}, Vector: {token_vector[:5]}")  # Displaying first 5 dimensions of the vector for brevity

Token: Apple, Vector: [-1.2311026  -1.1917264   0.15840489  0.35988116  0.6805322 ]
Token: is, Vector: [-1.0027504  -0.25142258  0.28945386  0.7576598  -0.58256423]
Token: looking, Vector: [-0.41153106  1.094019    0.73340464  0.08318283 -1.0782878 ]
Token: at, Vector: [ 1.3064765   1.9255978   0.5234667  -1.0940402  -0.33415377]
Token: buying, Vector: [-0.38275096  0.8829504  -0.06646706  0.16533871 -0.43682557]
Token: a, Vector: [0.93501806 0.00710958 0.04742083 1.0769678  0.44846863]
Token: U.K., Vector: [-0.28209645 -1.3021066  -0.2161325   1.3588122   0.06865764]
Token: startup, Vector: [-0.7089213  -0.34339467  0.4557867  -0.7568426  -0.3378846 ]
Token: for, Vector: [-0.05590749  0.15916066  1.2973515  -0.43173665 -0.79201484]
Token: $, Vector: [-0.6496361   1.2837512   0.17862085  0.393975    1.7535145 ]
Token: 1, Vector: [-1.1002016   0.63555384  5.3034716   0.27870944  3.1097717 ]
Token: billion, Vector: [-1.4627483  0.5298873 -1.3364623  1.4983535  3.1686215]
Token: ., Vector

Using NLTK:
NLTK does not have built-in capabilities for vector-based semantic analysis directly. However, you can use word2vec or GloVe pre-trained word vectors from external libraries like gensim to perform semantic analysis. Here's an example using gensim:

In [5]:
#!conda list scipy

In [6]:
#!conda install -c conda-forge gensim

In [7]:
#!conda install --force-reinstall scipy

In [8]:
import scipy
print(scipy.__version__)

1.10.1


In [9]:
#!conda update -n nlp_env scipy

In [10]:
from scipy.linalg import triu

In [11]:
import numpy as np
from scipy.linalg import triu

# Create a sample matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Extract the upper triangular part of the matrix
upper_triangular = triu(A)

print("Original Matrix:")
print(A)
print("\nUpper Triangular Part:")
print(upper_triangular)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Upper Triangular Part:
[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [13]:
from scipy.linalg import triu

In [14]:
import nltk
from nltk.tokenize import word_tokenize
from gensim.models import KeyedVectors

# Ensure necessary resources are downloaded
nltk.download('punkt')

# Sample text
text = "Hello, how are you?"

# Tokenize text
tokens = word_tokenize(text)
print(tokens)

['Hello', ',', 'how', 'are', 'you', '?']


[nltk_data] Downloading package punkt to
[nltk_data]     /Users/vidyadharbendre/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [20]:
import os

path_to_model = '/Users/vidyadharbendre/nlp_workspace/learn_nlp_using_examples/GoogleNews-vectors-negative300.bin'
path_to_model

'/Users/vidyadharbendre/nlp_workspace/learn_nlp_using_examples/GoogleNews-vectors-negative300.bin'

In [21]:
if os.path.exists(path_to_model):
    word2vec_model = KeyedVectors.load_word2vec_format(path_to_model, binary=True)
else:
    print(f"Error: File '{path_to_model}' not found.")

In [22]:
import nltk
from nltk.tokenize import word_tokenize
from gensim.models import KeyedVectors

# Ensure necessary resources are downloaded
nltk.download('punkt')

# Load pre-trained Word2Vec model (for example purposes, using a small pre-trained model)
# You can download a larger model from gensim-data or use your own pre-trained model
word2vec_model = KeyedVectors.load_word2vec_format(path_to_model, binary=True)

# Example text
text = "Apple is looking at buying a U.K. startup for $1 billion."

# Tokenize the text
words = word_tokenize(text)

# Semantic analysis using Word2Vec
semantic_analysis_word2vec = [(word, word2vec_model[word]) for word in words if word in word2vec_model]

# Display token text and vector
for word, vector in semantic_analysis_word2vec:
    print(f"Word: {word}, Vector: {vector[:5]}")  # Displaying first 5 dimensions of the vector for brevity

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/vidyadharbendre/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Word: Apple, Vector: [-0.17480469  0.0300293  -0.21679688  0.15625    -0.35742188]
Word: is, Vector: [ 0.00704956 -0.07324219  0.171875    0.02258301 -0.1328125 ]
Word: looking, Vector: [ 0.02783203  0.25585938  0.15820312 -0.0480957  -0.05395508]
Word: at, Vector: [-0.05859375 -0.03759766  0.07275391  0.10888672  0.06640625]
Word: buying, Vector: [ 0.12109375  0.05664062 -0.2421875   0.18164062 -0.03637695]
Word: U.K., Vector: [ 0.11328125  0.07373047 -0.2890625   0.05639648 -0.11474609]
Word: startup, Vector: [ 0.0390625  -0.08251953  0.00311279 -0.07373047  0.10791016]
Word: for, Vector: [-0.01177979 -0.04736328  0.04467773  0.06347656 -0.01818848]
Word: $, Vector: [ 0.11376953 -0.11767578  0.06494141  0.1328125   0.05493164]
Word: 1, Vector: [ 0.05078125 -0.09326172  0.06494141  0.11425781 -0.06494141]
Word: billion, Vector: [0.04541016 0.02648926 0.09960938 0.13964844 0.01708984]


## Explanation:

What: This snippet demonstrates semantic analysis using NLTK for tokenization and Gensim's Word2Vec model for obtaining word vectors.

Why: NLTK is used for tokenization (word_tokenize) to break down the text into words. Gensim's Word2Vec model (KeyedVectors) is then loaded to obtain vector representations for each word.

How: After tokenizing the text (words = word_tokenize(text)), the script checks if each word exists in the loaded Word2Vec model (word in word2vec_model). If true, it retrieves the vector representation (word2vec_model[word]) for semantic analysis purposes.

## Summary
SpaCy offers an efficient way to perform semantic analysis by leveraging pre-trained word vectors.
NLTK provides tools for text processing and tokenization, which are essential for preparing text for semantic analysis.
Gensim's Word2Vec models enable the extraction of semantic information through word vectors, enhancing the understanding of textual context and meaning.
By using these libraries and models, developers can implement robust semantic analysis solutions for various NLP tasks effectively.